# Generated by Django 5.2.8 on 2026-07-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_penyewaan_email_tamu_penyewaan_nama_tamu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyewaan',
            name='nik_tamu',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('pelanggan', 'Pelanggan')], max_length=20),
        ),
    ]
