# Generated by Django 5.2.8 on 2026-07-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_penyewaan_nik_tamu_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunci', models.CharField(max_length=50, unique=True)),
                ('nilai', models.TextField(blank=True, null=True)),
                ('nilai_gambar', models.ImageField(blank=True, null=True, upload_to='pengaturan/')),
            ],
            options={
                'verbose_name': 'Pengaturan',
                'verbose_name_plural': 'Pengaturan',
            },
        ),
    ]
